parameters:
#    acme_store.example.class: Acme\StoreBundle\Example

services:
    acme_store.listener.request:
        class: Acme\StoreBundle\Controller\LocaleListener
        tags: [{ name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: -255 }]
        arguments: [ @service_container, "plain_value", %locale%]