parameters:
#    acme_store.example.class: Acme\StoreBundle\Example

services:
   
    kernel.listener.exceptio:
        class:  Acme\DemoBundle\EventListener\ExceptionListener
        tags: [{ name: kernel.event_listener, event: kernel.exception, method: onKernelException }]
        arguments: [@templating, @kernel]